### ISSUE TITLE
Port microsatellite models to BEAST2

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#4]
Port Jessie Wu's microsatellite models in BEAST1 to BEAST2

**Comment by rbouckaert** [comment]
There is the beastVNTR package https://github.com/arjun-1/BEASTvntr that works with BEAST v2.4.3 that supports microsatellite models and is parameterised as Jessie's model, but it does not implement the model averaging of Jessie's model.
